# Generated by Django 4.2.7 on 2026-04-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_name', models.CharField(choices=[('fajr', 'Fajr'), ('sunrise', 'Sunrise'), ('dhuhr', 'Dhuhr'), ('asr', 'Asr'), ('maghrib', 'Maghrib'), ('isha', 'Isha')], max_length=20)),
                ('adhan_reciter', models.CharField(default='mishary', max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Prayer Notifications',
                'ordering': ['prayer_name'],
            },
        ),
        migrations.CreateModel(
            name='Reciter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciter_id', models.CharField(help_text='Unique identifier for reciter', max_length=50, unique=True)),
                ('name_ar', models.CharField(help_text='Arabic name', max_length=200)),
                ('name_en', models.CharField(help_text='English name', max_length=200)),
                ('transliteration', models.CharField(blank=True, max_length=100)),
                ('style', models.CharField(choices=[('murattal', 'Murattal'), ('mujawwad', 'Mujawwad'), ('tajweed', 'Tajweed')], default='murattal', max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('bio_en', models.TextField(blank=True, help_text='English biography')),
                ('bio_ru', models.TextField(blank=True, help_text='Russian biography')),
                ('bio_uz', models.TextField(blank=True, help_text='Uzbek biography')),
                ('server_url', models.URLField(help_text='Base URL for audio files')),
                ('edition', models.CharField(help_text='Quranic edition code (e.g., ar.alafasy)', max_length=100)),
                ('photo_url', models.URLField(blank=True)),
                ('initial_letter', models.CharField(blank=True, max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Reciters',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.IntegerField()),
                ('ayah_number', models.IntegerField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Bookmarks',
                'ordering': ['-created_at'],
                'unique_together': {('surah_number', 'ayah_number')},
            },
        ),
    ]
